### ISSUE TITLE
Incompatible version of Grafana

### ISSUE THREAD

**Issue by jasonpadman** [NetApp-StorageGRID/storagegrid-monitoring#1]
Message from customer:
Grafana version that is installed in the docker container is not correct, it doesn’t work with ElasticSearch 5 (in the docker composer is required ES 5.1.1).

We changed the docker-composer.yml file and requested a Grafana 4.1.1 image. Also, the datasources have to use the version 5.x in the ElasticSerach details properties. 

Also there is a option in Grafana datasource plugin that should be preselected to 5.x. In version 4.0.2 there is no 5.x option, so it can’t work with the ElasticSearch 5.1.1 that is deployed with docker:
 
-          Logstash 5.1.1 OK
-          ElasticSearch 5.1.1 OK
-          Grafana 4.0.2 -> 4.1.1

With that change, the dashboard “StorageGRID Webscale” works as expected using the indexes “logstash-*” (at least there is no errors and seems to be data in some graphs). 

However the dashboard “StorageGRID Webscale Monitoring” still has problems because the datasource is configured to use the “counters-*” indexes in ElasticSearch, but there is no indexes with that name. Is there another source of data to feed in ElasticSearch? or the index pattern is wrong?

**Comment by yeddie** [comment]
Try latest update
